### ISSUE TITLE
Is there any way to use polar subplots on a euclidean main plot?

### ISSUE THREAD

**Issue by mschubert** [garrettgman/ggsubplot#12]
This is related to [this question on Stackoverflow](https://stackoverflow.com/questions/20052250/pie-charts-in-ggsubplot-ggplot2).

I can easily produce a plotting command that displays stacked bar graphs on a map, [derived from the examples shown here](http://blog.revolutionanalytics.com/2012/09/visualize-complex-data-with-subplots.html):

```r
library(ggplot2)
library(ggsubplot)
library(ggmap)
qmap('afghanistan', zoom = 6, maptype = 'toner', extent = 'panel') +
    geom_subplot2d(
        aes(lon, lat,
            subplot = geom_bar(aes(x=factor(1), y=..count.., fill = victim))
    ), bins = c(15,12), ref = NULL, width = rel(0.8),
    data = casualties
)
```

Is there a way to show the stacked bar plots as pie charts? Usually, I would add `+ coord_polar(theta="y")`, but adding it to the subplot produces a `non-numeric argument to binary operator` error and adding it to the whole plot transforms the map into polar coordinates:

```r
# this example produces a "non-numeric argument to binary operator" error
qmap('afghanistan', zoom = 6, maptype = 'toner', extent = 'panel') +
    geom_subplot2d(
        aes(lon, lat,
        subplot = geom_bar(aes(x=factor(1), y=..count.., fill = victim)) + 
            coord_polar(theta="y") 
    ), bins = c(15,12), ref = NULL, width = rel(0.8),
    data = casualties
)
```

```r
# this example transforms the whole thing into polar coordinates
qmap('afghanistan', zoom = 6, maptype = 'toner', extent = 'panel') +
    geom_subplot2d(
        aes(lon, lat,
        subplot = geom_bar(aes(x=factor(1), y=..count.., fill = victim))
    ), bins = c(15,12), ref = NULL, width = rel(0.8),
    data = casualties
) + coord_polar(theta="y")
```

**Comment by hadley** [comment]
Not currently - unfortunately it would be very difficult to implement in ggplot2. Hopefully this will be possible in ggvis (once I figure out how to add subplots)
