### ISSUE TITLE
remove ggsubplot from CRAN or update package description

### ISSUE THREAD

**Issue by mkoohafkan** [garrettgman/ggsubplot#14]
Based on my own tests and [this StackOverflow answer](http://stackoverflow.com/a/20468836/2375551), `ggsubplot` does not work with `R v3.2.0` and/or `ggplot2 v1.0.1`. It would be great if `ggsubplot` could be removed from CRAN, or the `depends` and `imports` directives were updated to reflect the fact that older installations of R and/or ggplot2 are needed for the package to work correctly.

**Comment by hadley** [comment]
Should be fixed now.
