### ISSUE TITLE
Error: ggsubplots do not support facetting

### ISSUE THREAD

**Issue by cpsievert** [garrettgman/ggsubplot#6]
I guess this may be more of a request than an issue.

I would like to integrate `ggsubplot` functionality within my package `pitchRx`. Here is a minimal example of something I would like to achieve.

```s
library(ggsubplot)
library(pitchRx)
data(pitches)
pitches$px <- as.numeric(pitches$px)
pitches$pz <- as.numeric(pitches$pz)
#works
ggplot(data=pitches)+geom_subplot2d(aes(x=px, y=pz, 
                    subplot = geom_bar(aes(x=des, fill = des))))
#doesn't work
ggplot(data=pitches)+geom_subplot2d(aes(x=px, y=pz, 
                    subplot = geom_bar(aes(x=des, fill = des))))+facet_wrap(~stand)
```

Is there a theoretical reason why facetting isn't supported in `ggsubplot`? Or is it just a difficult problem? By the way, this package is quite awesome and I think it has a lot of potential!

**Comment by hadley** [comment]
I'm going to close this for now - it should (eventually) be straightforward in ggvis
